---
- name: This playbook is to create user
  hosts: all
  become: True
  tasks: 
  - name: Creating User John
    user: 
      name: john
  tasks:
  - name: Deleting User John
    user:
      name: john
      state: absent
      remove: True

