---
- name: This playbook will install httpd
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
    notify: start apache

  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666  

  handlers:
  - name: start apache
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"


