---
- name: This playbook will install httpd
  hosts: all
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Start apache
    service:
      name: apache
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

   -name: Start apache2
    sevice:
      name: apache2
      satte: stated
    when: ansible_os_family == "Debian"

  - name: Copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

