---
- name: Download and Setup tomcat server
  hosts: all
  become: true
  tasks:
  - name: installing java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Downloading Tomcat Package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
      dest: /opt

  - name: Untar apache package
    unarchive:
      src: /opt/apache-tomcat-10.0.27.tar.gz
      dest: /opt
      remote_src: yes

  - name: Adding execution permission on startup.sh
    file:
      path: /opt/apache-tomcat-10.0.27/bin/startup.sh
      mode: 0777

  - name: starting Tomcat server
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-10.0.27/bin





