---
- name: This playbook will stop and uninstall httpd service
  hosts: all
  become: true
  tasks:
  - name: Stopping httpd service
    service:
      name: httpd
      state: stopped

  - name: Uninstalling httpd service
    yum:
      name: httpd
      state: removed

